### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by YDJSZY** [maja0270558/majascan_flutter#16]
majascan-0.3.5/ios/Classes/C
    rossView.swift:58:101: error: type 'UIApplication' has no member 'willEnterForegroundNotification'
            NotificationCenter.default.addObserver(self, selector: #selector(appEnterForeground),
            name: UIApplication.willEnterForegroundNotification, object: nil)

majascan-0.3.5/ios/Classes/C
    rossView.swift:59:101: error: type 'UIApplication' has no member 'willResignActiveNotification'
            NotificationCenter.default.addObserver(self, selector: #selector(appEnterBackground),
            name: UIApplication.willResignActiveNotification, object: nil)

**Comment by maja0270558** [comment]
Please check your project's Swift version. 0.3.5 is base on Swift5.
