### ISSUE TITLE
scan area is small , is there any way to make it big, custom options to set

### ISSUE THREAD

**Issue by kprathap23** [maja0270558/majascan_flutter#18]
Thank you for the good library..

![Screenshot_2020-03-13-19-05-00-379](https://user-images.githubusercontent.com/2254065/76626037-6855b500-655e-11ea-9476-f21486f8cc4f.jpg)

**Comment by maja0270558** [comment]
Hi, thanks for creating an issue. Add custom parameter `scanAreaScale` in 0.3.6 version and fix some iOS bug.
