### ISSUE TITLE
iOS ** BUILD FAILED **

### ISSUE THREAD

**Issue by sheatming** [maja0270558/majascan_flutter#2]
Running pod install...
Running Xcode build...
Xcode build done.                                            1.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Unable to run command 'StripNIB MAJAOverlay.nib' - this target might include its own product.
    Unable to run command 'StripNIB MAJAOverlay~iphone.nib' - this target might include its own product.
    Unable to run command 'StripNIB MAJAOverlay~ipad.nib' - this target might include its own product.
    Unable to run command 'StripNIB MAJAScannerController.nib' - this target might include its own product.
    Unable to run command 'StripNIB MAJAScannerController~iphone.nib' - this target might include its own product.
    Unable to run command 'StripNIB MAJAScannerController~ipad.nib' - this target might include its own product.

Could not build the application for the simulator.
Error launching application on iPhone 6s Plus.

**Comment by maja0270558** [comment]
Please add **use_frameworks!** in your iOS Podfile target.

**Comment by sheatming** [comment]
//*****0.1.5*****//
Running pod install...                                              1.5s
Running Xcode build...                                                  
Xcode build done.                                            1.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/*/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/majascan-0.1.5/ios/Classes/MajascanPlugin.m:2:9: fatal error: 'majascan/majascan-Swift.h' file not found
    #import <majascan/majascan-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Encountered error while building for device.


//*****0.1.6*****//
Launching lib/main.dart on iPhone 6s Plus in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            2.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/*/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/majascan-0.1.6/ios/Classes/CrossView.swift:72:40: error: 'kCAFillRuleEvenOdd' has been renamed to 'CAShapeLayerFillRule.evenOdd'
            backgroundMaskLayer.fillRule = kCAFillRuleEvenOdd
                                           ^~~~~~~~~~~~~~~~~~
                                           CAShapeLayerFillRule.evenOdd
    QuartzCore.kCAFillRuleEvenOdd:3:12: note: 'kCAFillRuleEvenOdd' was obsoleted in Swift 3
    public let kCAFillRuleEvenOdd: CAShapeLayerFillRule
               ^
    /Users/*/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/majascan-0.1.6/ios/Classes/MAJAOverlay.swift:33:30: error: 'kCAFillRuleEvenOdd' has been renamed to 'CAShapeLayerFillRule.evenOdd'
            maskLayer.fillRule = kCAFillRuleEvenOdd
                                 ^~~~~~~~~~~~~~~~~~
                                 CAShapeLayerFillRule.evenOdd
    QuartzCore.kCAFillRuleEvenOdd:3:12: note: 'kCAFillRuleEvenOdd' was obsoleted in Swift 3
    public let kCAFillRuleEvenOdd: CAShapeLayerFillRule
               ^
    === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/*/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/majascan-0.1.6/ios/Classes/MAJAScannerController.swift:73:23: warning: value 'output' was defined but never used; consider replacing with boolean test
                guard let output = metadataOutput else {
                      ~~~~^~~~~~~~~
                                                  != nil

Could not build the application for the simulator.
Error launching application on iPhone 6s Plus.
