### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by weiwei00200** [maja0270558/majascan_flutter#20]
安卓手機掃碼後頁面關閉了但是沒回調。
`2020-04-03 13:49:40.116 5282-6164/com.transport.taojiyun E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
    java.lang.RuntimeException: Camera is being used after Camera.release() was called
        at android.hardware.Camera.setHasPreviewCallback(Native Method)
        at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:967)
        at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:169)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by heartbeat986** [comment]
I get same problem when i use webview_plugin at same time. The reason is that  in this plugin's  `Request_Scan` is same with webview_plugin's, so change  `Request_Scan` value in `MajascanPlugin` file can be userful。

**Comment by heartbeat986** [comment]
> 安卓手機掃碼後頁面關閉了但是沒回調。
> `2020-04-03 13:49:40.116 5282-6164/com.transport.taojiyun E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called java.lang.RuntimeException: Camera is being used after Camera.release() was called at android.hardware.Camera.setHasPreviewCallback(Native Method) at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:967) at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:169) at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1278) at android.os.Handler.dispatchMessage(Handler.java:112) at android.os.Looper.loop(Looper.java:216) at android.os.HandlerThread.run(HandlerThread.java:65)`

I get same problem when i use webview_plugin at same time. The reason is that in this plugin's Request_Scan is same with webview_plugin's, so change Request_Scan value in MajascanPlugin file can be userful。
