### ISSUE TITLE
Deprecated APPLICATION_ID - build fails

### ISSUE THREAD

**Issue by david-alejandro-reyes-milian** [maja0270558/majascan_flutter#28]
related to: https://android.googlesource.com/platform/tools/base/+/51644d6f302ea8c3616d98afde0b4ee30d7d4741

locally solved it by replacing the deprecated APPLICATION_ID. Check the link. Please fix.

**Comment by kuhnroyal** [comment]
This has been removed in gradle tools 4.0.0

**Comment by maja0270558** [comment]
Thanks for all your help kuhnroyal.
