### ISSUE TITLE
Translations for more languages

### ISSUE THREAD

**Issue by lyio** [maja0270558/majascan_flutter#37]
Is there a way to add translations for more languages in the App using this package?

I tried simply adding the same keys to my `.strings` files in XCode and I tried creating my own `majascan.strings` file in my project to override/add translations for German.

Is there a way to do this in iOS or do I have to add the translations here in the package?

**Comment by maja0270558** [comment]
Unforturnly you will need to do that if you want to add more translations. Because majascan get localize string from bundle `majascanLocalizeBundle` which specify in `majascan.podspec` -> `s.resource_bundles`. :[
