### ISSUE TITLE
Execution failed for task ':majascan:compileDebugKotlin'

### ISSUE THREAD

**Issue by MisterioRee** [maja0270558/majascan_flutter#39]
I am trying to build after long time it's throwing an Error:
![Capture](https://user-images.githubusercontent.com/18234947/107510077-e8482d00-6bbc-11eb-843c-82235f5a6884.PNG)

It's been working for long time i do have a production version of this App, this one suddenly appaired from nowhere.

**Comment by GomajiGeorgeHsu** [comment]
We already push a new version (0.4)，please try it again.
